#!/bin/bash

set -e

BASEDIR=$(dirname "$0")
FILE_PATH=$1
FILE_PATH_STEM=${FILE_PATH%.lat}

$BASEDIR/target/release/latte ${FILE_PATH_STEM}.lat > ${FILE_PATH_STEM}.s

clang -o ${FILE_PATH_STEM} -masm=intel ${FILE_PATH_STEM}.s $BASEDIR/lib/runtime.o
